### ISSUE TITLE
Questions about the pretrained weights

### ISSUE THREAD

**Issue by wangkiw** [maorash/NeRN#26]
Hi, 

Thanks for your exciting work! But where can I get these pre-trained weights (e.g., https://github.com/maorash/NeRN/blob/bf164c8b035aee37045e0cf8c233923e57b39f5a/NeRN/experiments/resnet20/cifar10/cifar10_resnet20_regular_160.yaml#L4)?

**Comment by maorash** [comment]
Hey,
Sorry for the delay, we've been updating the framework in addition to uploading the relevant checkpoints.
The README file now refers to the original model's pretrained weights and to NeRN checkpoints trained to reconstruct these models 😄

**Comment by maorash** [comment]
Sorry for the delay, pretrained weights have been added to git :)
