### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by minhquoc0712** [maorash/NeRN#27]
Hi, thank you for your interesting research.

I have one question. The work focuses on reconstructing the kernel in the CNN layer, but the linear layer can also be interpreted as a 1x1 convolution layer. Have you done any experiments with this approach?

**Comment by maorash** [comment]
Hello,

You are correct. The final linear layer can be interpreted as a 1x1 convolution, but this is not yet implemented in the code.
We have neglected the implementation for simplicity, and because at the time of publication, we did not see the theoretical benefit for it (except for completeness).
